spring.application.name=sistema-contratacion
# Conexión a la Base de Datos PostgreSQL

# Configuración de la conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/contrataciones_db
spring.datasource.username=postgres
spring.datasource.password=12345

# Driver de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 'update' creará automáticamente las tablas si no existen en tu Postgres, sin borrar los datos existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8081

# Permite subir archivos CSV de hasta 10 MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
